### ISSUE TITLE
Scripts execution failed

### ISSUE THREAD

**Issue by Franklin905** [yahoo/maaf#4]
Hi, 
I'm interested in your work and would like to reproduce the results in the paper. However, after I git clone the repository and ran "bash experiment_scripts/paper/no_imfq_pretrain.sh" in the directory of maaf-master, I got many error messages related to ModuleNotFoundError.
Did I miss some steps before running the scripts?
I screenshotted the error messages and attached the picture below.
![1](https://user-images.githubusercontent.com/56862333/174628587-7c13090e-1208-4d33-b09d-98933c9fcc8c.jpg)

**Comment by emdodds** [comment]
Hi and thanks for your interest. You need to install the package. I recommend an editable install in case you want to tweak something: navigate to the root directory of this repository in your terminal and type `pip install -e .`

**Comment by YXTR** [comment]
@emdodds  Hi, I also hope to reproduce the experimental results but fail to execute scripts. 
After installing the package and running `bash experiment_scripts/paper/no_imfq_pretrain.sh`, I got the following message (Repeated several times):
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    main.main()
  File "/home/user/maaf/src/maaf/main.py", line 41, in main
    cfg = setup(args, modify_exp_name=append_datetime)
  File "/home/user/maaf/src/maaf/main.py", line 22, in setup
    cfg = get_config()
  File "/home/user/maaf/src/maaf/config/config.py", line 9, in get_config
    from .defaults import _C
  File "/home/user/maaf/src/maaf/config/defaults.py", line 17, in <module>
    _C.MODEL.WEIGHTS = None  # load from this path
  File "/home/user/anaconda3/envs/iq/lib/python3.8/site-packages/yacs/config.py", line 155, in __setattr__
    _assert_with_logging(
  File "/home/user/anaconda3/envs/iq/lib/python3.8/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key WEIGHTS; valid types = {<class 'list'>, <class 'tuple'>, <class 'int'>, <class 'bool'>, <class 'str'>, <class 'float'>}
```
According to the error message, I have to give a model path in the config file; I'm wondering where I should get the model weights for this experiment (`no_imfq_pretrain.sh`). 

In addition, I found that this folder `/home/default/ephemeral_drive/Data/` contains the datasets. I want to know its directory structure so I can change it to my corresponding address in the configuration file.

**Comment by jackculpepper** [comment]
Did CLIP install properly? The weights should be here:

```
$ ls -l ~/.cache/clip/
total 250080
-rw-rw-r-- 1 jack jack 255827503 Jul  7 17:46 RN50.pt
$
```

An easy way to set up FashionIQ is to check out these two repos in the same parent directory as `maaf`:

```
git clone https://github.com/XiaoxiaoGuo/fashion-iq.git
git clone https://github.com/hongwang600/fashion-iq-metadata.git
```

..then write a script to use the asin2url maps in `fashion-iq-metadata` to download the images into `dress`, `shirt`, and `toptee` subdirectories of an `img` directory in `fashion-iq`. Here is how the result should be structured:

```
$ ls fashion-iq
captions/  image_splits/  img/	README.md  start_kit/  transformer/
$ ls fashion-iq/img
dress/	shirt/	toptee/
$ ls -l fashion-iq/img/dress | head -5
total 115396
-rw-rw-r-- 1 jack jack 24336 Nov 16  2007 B00014NGF6
-rw-rw-r-- 1 jack jack  8882 Nov 15  2007 B0006HJ8FU
-rw-rw-r-- 1 jack jack  8538 Jul 24  2013 B0006HJ91S
-rw-rw-r-- 1 jack jack  9644 Jul  1  2010 B0006HJBCA
```

Now you can edit `experiment_scripts/paper/no_imfq_pretrain.sh` and point `DATASET.PATH` to the `fashion-iq` directory.

```
$ grep DATASET.PATH experiment_scripts/paper/no_imfq_pretrain.sh
  DATASET.PATH ../fashion-iq \
$
```

Please let me know if this works for you. If so, I will update the README to incorporate these instructions.

**Comment by YXTR** [comment]
> 
@jackculpepper 
Thanks for the detailed reply.

I found the error reported above is because pip installed an older version of YACS (`yacs==1.6.0`), which does not support the `None` type in `./src/maaf/config/defaults.py`. After I updated YACS to 1.8.0, the issue was solved.

The dataset setup instruction works for me.
